export interface Pais {
  code: string;
  label: string;
}

// Lista completa de países (ISO 3166-1 alpha-2), nombre en español, orden alfabético.
export const PAISES: Pais[] = [
  { code: "AF", label: "Afganistán" },
  { code: "AL", label: "Albania" },
  { code: "DE", label: "Alemania" },
  { code: "AD", label: "Andorra" },
  { code: "AO", label: "Angola" },
  { code: "AG", label: "Antigua y Barbuda" },
  { code: "SA", label: "Arabia Saudita" },
  { code: "DZ", label: "Argelia" },
  { code: "AR", label: "Argentina" },
  { code: "AM", label: "Armenia" },
  { code: "AU", label: "Australia" },
  { code: "AT", label: "Austria" },
  { code: "AZ", label: "Azerbaiyán" },
  { code: "BS", label: "Bahamas" },
  { code: "BD", label: "Bangladés" },
  { code: "BB", label: "Barbados" },
  { code: "BH", label: "Baréin" },
  { code: "BE", label: "Bélgica" },
  { code: "BZ", label: "Belice" },
  { code: "BJ", label: "Benín" },
  { code: "BY", label: "Bielorrusia" },
  { code: "BO", label: "Bolivia" },
  { code: "BA", label: "Bosnia y Herzegovina" },
  { code: "BW", label: "Botsuana" },
  { code: "BR", label: "Brasil" },
  { code: "BN", label: "Brunéi" },
  { code: "BG", label: "Bulgaria" },
  { code: "BF", label: "Burkina Faso" },
  { code: "BI", label: "Burundi" },
  { code: "BT", label: "Bután" },
  { code: "CV", label: "Cabo Verde" },
  { code: "KH", label: "Camboya" },
  { code: "CM", label: "Camerún" },
  { code: "CA", label: "Canadá" },
  { code: "QA", label: "Catar" },
  { code: "TD", label: "Chad" },
  { code: "CL", label: "Chile" },
  { code: "CN", label: "China" },
  { code: "CY", label: "Chipre" },
  { code: "VA", label: "Ciudad del Vaticano" },
  { code: "CO", label: "Colombia" },
  { code: "KM", label: "Comoras" },
  { code: "KP", label: "Corea del Norte" },
  { code: "KR", label: "Corea del Sur" },
  { code: "CI", label: "Costa de Marfil" },
  { code: "CR", label: "Costa Rica" },
  { code: "HR", label: "Croacia" },
  { code: "CU", label: "Cuba" },
  { code: "DK", label: "Dinamarca" },
  { code: "DM", label: "Dominica" },
  { code: "EC", label: "Ecuador" },
  { code: "EG", label: "Egipto" },
  { code: "SV", label: "El Salvador" },
  { code: "AE", label: "Emiratos Árabes Unidos" },
  { code: "ER", label: "Eritrea" },
  { code: "SK", label: "Eslovaquia" },
  { code: "SI", label: "Eslovenia" },
  { code: "ES", label: "España" },
  { code: "US", label: "Estados Unidos" },
  { code: "EE", label: "Estonia" },
  { code: "SZ", label: "Esuatini" },
  { code: "ET", label: "Etiopía" },
  { code: "PH", label: "Filipinas" },
  { code: "FI", label: "Finlandia" },
  { code: "FJ", label: "Fiyi" },
  { code: "FR", label: "Francia" },
  { code: "GA", label: "Gabón" },
  { code: "GM", label: "Gambia" },
  { code: "GE", label: "Georgia" },
  { code: "GH", label: "Ghana" },
  { code: "GD", label: "Granada" },
  { code: "GR", label: "Grecia" },
  { code: "GT", label: "Guatemala" },
  { code: "GY", label: "Guyana" },
  { code: "GN", label: "Guinea" },
  { code: "GQ", label: "Guinea Ecuatorial" },
  { code: "GW", label: "Guinea-Bisáu" },
  { code: "HT", label: "Haití" },
  { code: "HN", label: "Honduras" },
  { code: "HU", label: "Hungría" },
  { code: "IN", label: "India" },
  { code: "ID", label: "Indonesia" },
  { code: "IQ", label: "Irak" },
  { code: "IR", label: "Irán" },
  { code: "IE", label: "Irlanda" },
  { code: "IS", label: "Islandia" },
  { code: "SB", label: "Islas Salomón" },
  { code: "IL", label: "Israel" },
  { code: "IT", label: "Italia" },
  { code: "JM", label: "Jamaica" },
  { code: "JP", label: "Japón" },
  { code: "JO", label: "Jordania" },
  { code: "KZ", label: "Kazajistán" },
  { code: "KE", label: "Kenia" },
  { code: "KG", label: "Kirguistán" },
  { code: "KI", label: "Kiribati" },
  { code: "KW", label: "Kuwait" },
  { code: "LA", label: "Laos" },
  { code: "LS", label: "Lesoto" },
  { code: "LV", label: "Letonia" },
  { code: "LB", label: "Líbano" },
  { code: "LR", label: "Liberia" },
  { code: "LY", label: "Libia" },
  { code: "LI", label: "Liechtenstein" },
  { code: "LT", label: "Lituania" },
  { code: "LU", label: "Luxemburgo" },
  { code: "MK", label: "Macedonia del Norte" },
  { code: "MG", label: "Madagascar" },
  { code: "MY", label: "Malasia" },
  { code: "MW", label: "Malaui" },
  { code: "MV", label: "Maldivas" },
  { code: "ML", label: "Malí" },
  { code: "MT", label: "Malta" },
  { code: "MA", label: "Marruecos" },
  { code: "MU", label: "Mauricio" },
  { code: "MR", label: "Mauritania" },
  { code: "MX", label: "México" },
  { code: "FM", label: "Micronesia" },
  { code: "MD", label: "Moldavia" },
  { code: "MC", label: "Mónaco" },
  { code: "MN", label: "Mongolia" },
  { code: "ME", label: "Montenegro" },
  { code: "MZ", label: "Mozambique" },
  { code: "MM", label: "Myanmar" },
  { code: "NA", label: "Namibia" },
  { code: "NR", label: "Nauru" },
  { code: "NP", label: "Nepal" },
  { code: "NI", label: "Nicaragua" },
  { code: "NE", label: "Níger" },
  { code: "NG", label: "Nigeria" },
  { code: "NO", label: "Noruega" },
  { code: "NZ", label: "Nueva Zelanda" },
  { code: "OM", label: "Omán" },
  { code: "NL", label: "Países Bajos" },
  { code: "PK", label: "Pakistán" },
  { code: "PW", label: "Palaos" },
  { code: "PA", label: "Panamá" },
  { code: "PG", label: "Papúa Nueva Guinea" },
  { code: "PY", label: "Paraguay" },
  { code: "PE", label: "Perú" },
  { code: "PL", label: "Polonia" },
  { code: "PT", label: "Portugal" },
  { code: "GB", label: "Reino Unido" },
  { code: "CF", label: "República Centroafricana" },
  { code: "CZ", label: "República Checa" },
  { code: "CG", label: "República del Congo" },
  { code: "CD", label: "República Democrática del Congo" },
  { code: "DO", label: "República Dominicana" },
  { code: "RW", label: "Ruanda" },
  { code: "RO", label: "Rumania" },
  { code: "RU", label: "Rusia" },
  { code: "WS", label: "Samoa" },
  { code: "KN", label: "San Cristóbal y Nieves" },
  { code: "SM", label: "San Marino" },
  { code: "VC", label: "San Vicente y las Granadinas" },
  { code: "LC", label: "Santa Lucía" },
  { code: "ST", label: "Santo Tomé y Príncipe" },
  { code: "SN", label: "Senegal" },
  { code: "RS", label: "Serbia" },
  { code: "SC", label: "Seychelles" },
  { code: "SL", label: "Sierra Leona" },
  { code: "SG", label: "Singapur" },
  { code: "SY", label: "Siria" },
  { code: "SO", label: "Somalia" },
  { code: "LK", label: "Sri Lanka" },
  { code: "ZA", label: "Sudáfrica" },
  { code: "SD", label: "Sudán" },
  { code: "SS", label: "Sudán del Sur" },
  { code: "SE", label: "Suecia" },
  { code: "CH", label: "Suiza" },
  { code: "SR", label: "Surinam" },
  { code: "TH", label: "Tailandia" },
  { code: "TW", label: "Taiwán" },
  { code: "TZ", label: "Tanzania" },
  { code: "TJ", label: "Tayikistán" },
  { code: "TL", label: "Timor Oriental" },
  { code: "TG", label: "Togo" },
  { code: "TO", label: "Tonga" },
  { code: "TT", label: "Trinidad y Tobago" },
  { code: "TN", label: "Túnez" },
  { code: "TM", label: "Turkmenistán" },
  { code: "TR", label: "Turquía" },
  { code: "TV", label: "Tuvalu" },
  { code: "UA", label: "Ucrania" },
  { code: "UG", label: "Uganda" },
  { code: "UY", label: "Uruguay" },
  { code: "UZ", label: "Uzbekistán" },
  { code: "VU", label: "Vanuatu" },
  { code: "VE", label: "Venezuela" },
  { code: "VN", label: "Vietnam" },
  { code: "YE", label: "Yemen" },
  { code: "DJ", label: "Yibuti" },
  { code: "ZM", label: "Zambia" },
  { code: "ZW", label: "Zimbabue" },
];
