export interface ZonaHoraria {
  id: string; // identificador IANA (ej: "America/Argentina/Buenos_Aires") — es el estándar que entienden todos los sistemas
  label: string;
}

/**
 * Lista curada de zonas horarias — no son las ~424 que existen en la
 * base IANA completa (sería una lista gigante e inmanejable para elegir a
 * mano), sino las que cubren razonablemente bien todos los países y las
 * variaciones más comunes dentro de cada uno (¡ideal para cuando alguien
 * quiere corregir la que se le puso por default!).
 */
export const ZONAS_HORARIAS: ZonaHoraria[] = [
  { id: "Pacific/Midway", label: "Midway (UTC-11)" },
  { id: "Pacific/Honolulu", label: "Honolulu (UTC-10)" },
  { id: "America/Anchorage", label: "Anchorage (UTC-9)" },
  { id: "America/Tijuana", label: "Tijuana (UTC-8)" },
  { id: "America/Los_Angeles", label: "Los Ángeles (UTC-8)" },
  { id: "America/Vancouver", label: "Vancouver (UTC-8)" },
  { id: "America/Denver", label: "Denver (UTC-7)" },
  { id: "America/Phoenix", label: "Phoenix (UTC-7)" },
  { id: "America/Chihuahua", label: "Chihuahua (UTC-7)" },
  { id: "America/Chicago", label: "Chicago (UTC-6)" },
  { id: "America/Mexico_City", label: "Ciudad de México (UTC-6)" },
  { id: "America/Guatemala", label: "Guatemala (UTC-6)" },
  { id: "America/El_Salvador", label: "San Salvador (UTC-6)" },
  { id: "America/Tegucigalpa", label: "Tegucigalpa (UTC-6)" },
  { id: "America/Managua", label: "Managua (UTC-6)" },
  { id: "America/Costa_Rica", label: "San José (UTC-6)" },
  { id: "America/Regina", label: "Regina (UTC-6)" },
  { id: "America/New_York", label: "Nueva York (UTC-5)" },
  { id: "America/Toronto", label: "Toronto (UTC-5)" },
  { id: "America/Havana", label: "La Habana (UTC-5)" },
  { id: "America/Panama", label: "Panamá (UTC-5)" },
  { id: "America/Bogota", label: "Bogotá (UTC-5)" },
  { id: "America/Lima", label: "Lima (UTC-5)" },
  { id: "America/Guayaquil", label: "Guayaquil (UTC-5)" },
  { id: "America/Jamaica", label: "Jamaica (UTC-5)" },
  { id: "America/Nassau", label: "Nassau (UTC-5)" },
  { id: "America/Caracas", label: "Caracas (UTC-4)" },
  { id: "America/La_Paz", label: "La Paz (UTC-4)" },
  { id: "America/Santo_Domingo", label: "Santo Domingo (UTC-4)" },
  { id: "America/Halifax", label: "Halifax (UTC-4)" },
  { id: "America/Puerto_Rico", label: "Puerto Rico (UTC-4)" },
  { id: "America/Asuncion", label: "Asunción (UTC-4)" },
  { id: "America/Manaus", label: "Manaos (UTC-4)" },
  { id: "America/St_Johns", label: "St. John's (UTC-3:30)" },
  { id: "America/Argentina/Buenos_Aires", label: "Buenos Aires (UTC-3)" },
  { id: "America/Sao_Paulo", label: "San Pablo (UTC-3)" },
  { id: "America/Montevideo", label: "Montevideo (UTC-3)" },
  { id: "America/Santiago", label: "Santiago (UTC-3/-4 según época del año)" },
  { id: "America/Cayenne", label: "Cayena (UTC-3)" },
  { id: "America/Godthab", label: "Nuuk (UTC-2)" },
  { id: "Atlantic/South_Georgia", label: "Georgias del Sur (UTC-2)" },
  { id: "Atlantic/Cape_Verde", label: "Cabo Verde (UTC-1)" },
  { id: "Atlantic/Azores", label: "Azores (UTC-1)" },
  { id: "UTC", label: "UTC" },
  { id: "Europe/London", label: "Londres (UTC+0)" },
  { id: "Europe/Lisbon", label: "Lisboa (UTC+0)" },
  { id: "Africa/Casablanca", label: "Casablanca (UTC+0)" },
  { id: "Africa/Accra", label: "Accra (UTC+0)" },
  { id: "Europe/Dublin", label: "Dublín (UTC+0)" },
  { id: "Europe/Madrid", label: "Madrid (UTC+1)" },
  { id: "Europe/Paris", label: "París (UTC+1)" },
  { id: "Europe/Berlin", label: "Berlín (UTC+1)" },
  { id: "Europe/Rome", label: "Roma (UTC+1)" },
  { id: "Europe/Amsterdam", label: "Ámsterdam (UTC+1)" },
  { id: "Europe/Brussels", label: "Bruselas (UTC+1)" },
  { id: "Europe/Vienna", label: "Viena (UTC+1)" },
  { id: "Europe/Zurich", label: "Zúrich (UTC+1)" },
  { id: "Europe/Warsaw", label: "Varsovia (UTC+1)" },
  { id: "Europe/Stockholm", label: "Estocolmo (UTC+1)" },
  { id: "Europe/Oslo", label: "Oslo (UTC+1)" },
  { id: "Europe/Copenhagen", label: "Copenhague (UTC+1)" },
  { id: "Europe/Budapest", label: "Budapest (UTC+1)" },
  { id: "Europe/Prague", label: "Praga (UTC+1)" },
  { id: "Europe/Belgrade", label: "Belgrado (UTC+1)" },
  { id: "Africa/Lagos", label: "Lagos (UTC+1)" },
  { id: "Africa/Algiers", label: "Argel (UTC+1)" },
  { id: "Africa/Tunis", label: "Túnez (UTC+1)" },
  { id: "Europe/Athens", label: "Atenas (UTC+2)" },
  { id: "Europe/Helsinki", label: "Helsinki (UTC+2)" },
  { id: "Europe/Bucharest", label: "Bucarest (UTC+2)" },
  { id: "Europe/Kyiv", label: "Kiev (UTC+2)" },
  { id: "Europe/Sofia", label: "Sofía (UTC+2)" },
  { id: "Africa/Cairo", label: "El Cairo (UTC+2)" },
  { id: "Africa/Johannesburg", label: "Johannesburgo (UTC+2)" },
  { id: "Asia/Jerusalem", label: "Jerusalén (UTC+2)" },
  { id: "Asia/Beirut", label: "Beirut (UTC+2)" },
  { id: "Asia/Amman", label: "Ammán (UTC+2)" },
  { id: "Europe/Moscow", label: "Moscú (UTC+3)" },
  { id: "Europe/Istanbul", label: "Estambul (UTC+3)" },
  { id: "Asia/Riyadh", label: "Riad (UTC+3)" },
  { id: "Asia/Baghdad", label: "Bagdad (UTC+3)" },
  { id: "Asia/Kuwait", label: "Kuwait (UTC+3)" },
  { id: "Asia/Qatar", label: "Doha (UTC+3)" },
  { id: "Africa/Nairobi", label: "Nairobi (UTC+3)" },
  { id: "Africa/Addis_Ababa", label: "Adís Abeba (UTC+3)" },
  { id: "Asia/Tehran", label: "Teherán (UTC+3:30)" },
  { id: "Asia/Dubai", label: "Dubái (UTC+4)" },
  { id: "Asia/Baku", label: "Bakú (UTC+4)" },
  { id: "Asia/Yerevan", label: "Ereván (UTC+4)" },
  { id: "Asia/Tbilisi", label: "Tiflis (UTC+4)" },
  { id: "Asia/Kabul", label: "Kabul (UTC+4:30)" },
  { id: "Asia/Karachi", label: "Karachi (UTC+5)" },
  { id: "Asia/Tashkent", label: "Taskent (UTC+5)" },
  { id: "Asia/Yekaterinburg", label: "Ekaterimburgo (UTC+5)" },
  { id: "Asia/Kolkata", label: "Bombay / Nueva Delhi (UTC+5:30)" },
  { id: "Asia/Colombo", label: "Colombo (UTC+5:30)" },
  { id: "Asia/Kathmandu", label: "Katmandú (UTC+5:45)" },
  { id: "Asia/Dhaka", label: "Daca (UTC+6)" },
  { id: "Asia/Almaty", label: "Almaty (UTC+6)" },
  { id: "Asia/Yangon", label: "Rangún (UTC+6:30)" },
  { id: "Asia/Bangkok", label: "Bangkok (UTC+7)" },
  { id: "Asia/Jakarta", label: "Yakarta (UTC+7)" },
  { id: "Asia/Ho_Chi_Minh", label: "Ho Chi Minh (UTC+7)" },
  { id: "Asia/Novosibirsk", label: "Novosibirsk (UTC+7)" },
  { id: "Asia/Shanghai", label: "Shanghái (UTC+8)" },
  { id: "Asia/Hong_Kong", label: "Hong Kong (UTC+8)" },
  { id: "Asia/Singapore", label: "Singapur (UTC+8)" },
  { id: "Asia/Manila", label: "Manila (UTC+8)" },
  { id: "Asia/Taipei", label: "Taipéi (UTC+8)" },
  { id: "Asia/Kuala_Lumpur", label: "Kuala Lumpur (UTC+8)" },
  { id: "Australia/Perth", label: "Perth (UTC+8)" },
  { id: "Asia/Irkutsk", label: "Irkutsk (UTC+8)" },
  { id: "Asia/Seoul", label: "Seúl (UTC+9)" },
  { id: "Asia/Tokyo", label: "Tokio (UTC+9)" },
  { id: "Australia/Darwin", label: "Darwin (UTC+9:30)" },
  { id: "Australia/Adelaide", label: "Adelaida (UTC+9:30)" },
  { id: "Australia/Sydney", label: "Sídney (UTC+10)" },
  { id: "Australia/Melbourne", label: "Melbourne (UTC+10)" },
  { id: "Australia/Brisbane", label: "Brisbane (UTC+10)" },
  { id: "Pacific/Guam", label: "Guam (UTC+10)" },
  { id: "Asia/Vladivostok", label: "Vladivostok (UTC+10)" },
  { id: "Pacific/Noumea", label: "Numea (UTC+11)" },
  { id: "Pacific/Auckland", label: "Auckland (UTC+12)" },
  { id: "Pacific/Fiji", label: "Fiyi (UTC+12)" },
  { id: "Pacific/Tongatapu", label: "Tonga (UTC+13)" },
];

/**
 * País (código ISO) -> zona horaria que le ponemos por default cuando
 * elige ese país — para países con varias zonas horarias, se usa la de
 * la ciudad más poblada/capital, que es lo que casi todo el mundo espera
 * como default. Igual siempre se puede cambiar a mano en el selector.
 */
export const PAIS_A_TIMEZONE_DEFAULT: Record<string, string> = {
  AF: "Asia/Kabul",
  AL: "Europe/Belgrade",
  DE: "Europe/Berlin",
  AD: "Europe/Madrid",
  AO: "Africa/Lagos",
  AG: "America/Puerto_Rico",
  SA: "Asia/Riyadh",
  DZ: "Africa/Algiers",
  AR: "America/Argentina/Buenos_Aires",
  AM: "Asia/Yerevan",
  AU: "Australia/Sydney",
  AT: "Europe/Vienna",
  AZ: "Asia/Baku",
  BS: "America/Nassau",
  BD: "Asia/Dhaka",
  BB: "America/Puerto_Rico",
  BH: "Asia/Qatar",
  BE: "Europe/Brussels",
  BZ: "America/Guatemala",
  BJ: "Africa/Lagos",
  BY: "Europe/Moscow",
  BO: "America/La_Paz",
  BA: "Europe/Belgrade",
  BW: "Africa/Johannesburg",
  BR: "America/Sao_Paulo",
  BN: "Asia/Kuala_Lumpur",
  BG: "Europe/Sofia",
  BF: "UTC",
  BI: "Africa/Johannesburg",
  BT: "Asia/Dhaka",
  CV: "Atlantic/Cape_Verde",
  KH: "Asia/Bangkok",
  CM: "Africa/Lagos",
  CA: "America/Toronto",
  QA: "Asia/Qatar",
  TD: "Africa/Lagos",
  CL: "America/Santiago",
  CN: "Asia/Shanghai",
  CY: "Europe/Athens",
  CO: "America/Bogota",
  KM: "Africa/Nairobi",
  KP: "Asia/Seoul",
  KR: "Asia/Seoul",
  CI: "UTC",
  CR: "America/Costa_Rica",
  HR: "Europe/Belgrade",
  CU: "America/Havana",
  DK: "Europe/Copenhagen",
  DM: "America/Puerto_Rico",
  EC: "America/Guayaquil",
  EG: "Africa/Cairo",
  SV: "America/El_Salvador",
  AE: "Asia/Dubai",
  ER: "Africa/Addis_Ababa",
  SK: "Europe/Prague",
  SI: "Europe/Belgrade",
  ES: "Europe/Madrid",
  US: "America/New_York",
  EE: "Europe/Helsinki",
  ET: "Africa/Addis_Ababa",
  PH: "Asia/Manila",
  FI: "Europe/Helsinki",
  FJ: "Pacific/Fiji",
  FR: "Europe/Paris",
  GA: "Africa/Lagos",
  GM: "UTC",
  GE: "Asia/Tbilisi",
  GH: "Africa/Accra",
  GD: "America/Puerto_Rico",
  GR: "Europe/Athens",
  GT: "America/Guatemala",
  GY: "America/Cayenne",
  GN: "UTC",
  GQ: "Africa/Lagos",
  GW: "UTC",
  HT: "America/New_York",
  HN: "America/Tegucigalpa",
  HU: "Europe/Budapest",
  IN: "Asia/Kolkata",
  ID: "Asia/Jakarta",
  IQ: "Asia/Baghdad",
  IR: "Asia/Tehran",
  IE: "Europe/Dublin",
  IS: "UTC",
  IL: "Asia/Jerusalem",
  IT: "Europe/Rome",
  JM: "America/Jamaica",
  JP: "Asia/Tokyo",
  JO: "Asia/Amman",
  KZ: "Asia/Almaty",
  KE: "Africa/Nairobi",
  KG: "Asia/Almaty",
  KI: "Pacific/Auckland",
  KW: "Asia/Kuwait",
  LA: "Asia/Bangkok",
  LS: "Africa/Johannesburg",
  LV: "Europe/Helsinki",
  LB: "Asia/Beirut",
  LR: "UTC",
  LY: "Africa/Cairo",
  LI: "Europe/Zurich",
  LT: "Europe/Helsinki",
  LU: "Europe/Brussels",
  MK: "Europe/Belgrade",
  MG: "Africa/Nairobi",
  MY: "Asia/Kuala_Lumpur",
  MW: "Africa/Johannesburg",
  MV: "Asia/Karachi",
  ML: "UTC",
  MT: "Europe/Rome",
  MA: "Africa/Casablanca",
  MU: "Asia/Dubai",
  MR: "UTC",
  MX: "America/Mexico_City",
  FM: "Pacific/Guam",
  MD: "Europe/Bucharest",
  MC: "Europe/Paris",
  MN: "Asia/Shanghai",
  ME: "Europe/Belgrade",
  MZ: "Africa/Johannesburg",
  MM: "Asia/Yangon",
  NA: "Africa/Johannesburg",
  NR: "Pacific/Auckland",
  NP: "Asia/Kathmandu",
  NI: "America/Managua",
  NE: "Africa/Lagos",
  NG: "Africa/Lagos",
  NO: "Europe/Oslo",
  NZ: "Pacific/Auckland",
  OM: "Asia/Dubai",
  NL: "Europe/Amsterdam",
  PK: "Asia/Karachi",
  PW: "Asia/Manila",
  PA: "America/Panama",
  PG: "Pacific/Guam",
  PY: "America/Asuncion",
  PE: "America/Lima",
  PL: "Europe/Warsaw",
  PT: "Europe/Lisbon",
  GB: "Europe/London",
  CF: "Africa/Lagos",
  CZ: "Europe/Prague",
  CG: "Africa/Lagos",
  CD: "Africa/Lagos",
  DO: "America/Santo_Domingo",
  RW: "Africa/Johannesburg",
  RO: "Europe/Bucharest",
  RU: "Europe/Moscow",
  SB: "Pacific/Noumea",
  WS: "Pacific/Auckland",
  KN: "America/Puerto_Rico",
  SM: "Europe/Rome",
  LC: "America/Puerto_Rico",
  VC: "America/Puerto_Rico",
  ST: "UTC",
  SN: "UTC",
  RS: "Europe/Belgrade",
  SC: "Asia/Dubai",
  SL: "UTC",
  SG: "Asia/Singapore",
  SY: "Asia/Beirut",
  SO: "Africa/Nairobi",
  LK: "Asia/Colombo",
  SZ: "Africa/Johannesburg",
  ZA: "Africa/Johannesburg",
  SD: "Africa/Cairo",
  SS: "Africa/Cairo",
  SE: "Europe/Stockholm",
  CH: "Europe/Zurich",
  SR: "America/Cayenne",
  TH: "Asia/Bangkok",
  TZ: "Africa/Nairobi",
  TJ: "Asia/Almaty",
  TL: "Asia/Manila",
  TG: "UTC",
  TO: "Pacific/Tongatapu",
  TT: "America/Puerto_Rico",
  TN: "Africa/Tunis",
  TM: "Asia/Tashkent",
  TR: "Europe/Istanbul",
  TV: "Pacific/Auckland",
  UA: "Europe/Kyiv",
  UG: "Africa/Nairobi",
  UY: "America/Montevideo",
  UZ: "Asia/Tashkent",
  VU: "Pacific/Noumea",
  VA: "Europe/Rome",
  VE: "America/Caracas",
  VN: "Asia/Ho_Chi_Minh",
  YE: "Asia/Riyadh",
  DJ: "Africa/Addis_Ababa",
  ZM: "Africa/Johannesburg",
  ZW: "Africa/Johannesburg",
};

export function zonaHorariaPorDefectoDePais(codigoPais: string): string {
  return PAIS_A_TIMEZONE_DEFAULT[codigoPais] ?? "UTC";
}
